on:
  workflow_dispatch:
    inputs:
      repo_1:
        type: boolean
        default: false
        description: Use Repo 1?
      repo_2:
        type: boolean
        default: false
        description: Use Repo 2?
jobs:
  repo-1-job:
    name: Repo 1 Job
    runs-on: ubuntu-latest
    if: github.event.inputs.repo_1 == 'true'
    steps:
      - run: echo "some test"
  
  repo-2-job:
    name: Repo 2 Job
    runs-on: ubuntu-latest
    if: github.event.inputs.repo_2 == 'true'
    steps:
      - run: echo "${{ github.event.inputs.repo_1 }}"
